from tkinter import *
root = Tk()
entry1 = Entry(root)
root.geometry("400x250")
entry1.grid(row = 0, column = 0, columnspan = 10)
l1 = Label(root, text = "Reg no")
l1.grid(row = 0, column = 0, ipadx = 20)
l2 = Label(root, text = "Name:")
l2.grid(row = 1, column = 0, ipadx = 20)
entry2 = Entry(root)
entry2.grid(row = 1, column = 0, columnspan = 10)
l3 = Label(root, text = "Dept")
l3.grid(row = 2, column = 0)
entry3 = Entry(root)
entry3.grid(row = 2, column = 0, columnspan = 10)
l4 = Label(root, text = "Gender")
l4.grid(row = 3, column = 0)
v = IntVar()
Radiobutton(root, text = "Male", variable = v, value = 1).grid(row = 3, column = 1)
Radiobutton(root, text = "Female", variable = v, value = 2).grid(row = 3, column = 2)
w = Spinbox(root, from_ = 17, to = 24)
w.grid(row = 4, column = 1)
l5 = Label(root, text = "Age")
l5.grid(row = 4, column = 0)
b1 = Button(root, text = "Insert")
b1.grid(row = 5, column = 0)
b2 = Button(root, text = "Delete")
b2.grid(row = 6, column = 0)
b3 = Button(root, text = "Update")
b3.grid(row = 5, column = 1)
b4 = Button(root, text = "Select")
b4.grid(row = 6, column = 1)
root = mainloop()